### ISSUE TITLE
Flower Breeds and Genes

### ISSUE THREAD

**Issue by AeonSake** [Treeki/CylindricalEarth#1]
Would it be possible to extract flower breeds and genes, especially the gene mutations? Also the shop-sold flowers (and their genes) would be helpful.
The current files only contain enums which don't hint at any genes.

**Comment by skent259** [comment]
I was just thinking about asking this too.  I would be interested in helping decode the percent chance of each flower breeding combination, but would definitely need a few pointers in the right direction

**Comment by AeonSake** [comment]
I wrote some very basic [breeding simulator](https://aeonsake.gitlab.io/acnh-flower-breeder/) but I'd love to expand it with gene breeding and gene mutations. Information out there is very limited as I've found only infos on ACPE (which has only a few flower types).

**Comment by genesy** [comment]
@AeonSake that looks amazing!

**Comment by ooraloo** [comment]
I was also interested in this topic, so I extracted some of the game files using Treeki's tools and found a file called FgFlowerHeredity. I'm having trouble figuring out what the column names are supposed to be, so maybe you guys might have some ideas.

https://github.com/ooraloo/Flower-Heredity/blob/master/FgFlowerHeredity.json

**Comment by GiovanH** [comment]
I've been diving into FgFlowerHeredity myself.

First off, 6aa33bf0 and 753336dd correspond to IDs from FgMainParam, which are IDs for plants and the like. 6aa33bf0 seems to be the FgId of the new plant that grows: always buds. 753336dd is an *optional* FgId of the same new plant, but in sprout form. 

That leaves 08d23365 | c7208ade | d5952530 | 6d294255 | f0fe7aec, which all range from 0 to 2, and seem to control the actual flower heredity. I haven't made any progress on finding a correlation with those yet.

**Comment by ooraloo** [comment]
Looks like someone else figured it out! They've determined that 3 of the columns that range from 0 to 2 are Red, Yellow, and White values (the fourth is a hidden factor relevant for blue roses). The boolean flag seems to indicate that those are the genes that are carried by seed flowers.

https://docs.google.com/spreadsheets/d/1rbYbQ0i3SuTu30KTma5dO4uuJWr_SjOZXA1l4UOIHWo/edit#gid=1106758232

**Comment by AeonSake** [comment]
Very interesting. I'm updating my data structures to account for those new informations. However, it is still unclear how offsprings carry over their parents genes (by simple combinations maybe?).

**Comment by skent259** [comment]
@ooraloo the spreadsheet you link to now links to another document: https://docs.google.com/document/d/1ARIQCUc5YVEd01D7jtJT9EEJF45m07NXhAm4fOpNvCs/edit where "Paleh" seems to have figured it all out, even the probabilities (based on Punnet Squares)

**Comment by AeonSake** [comment]
Awesome! I was reading up on flower gene manipulation before and assumed something like that would be used here. Mendelian inheritance makes the whole process a lot easier. Also it seams that unlike ACPC, ACNH doesn't have any mutations. Specific offsprings are only determined by their gene combinations.

**Comment by AeonSake** [comment]
I've updated my tool with all the new information. Thanks everyone, I believe this issue can be closed now.

**Comment by skent259** [comment]
FYI @AeonSake I think your breeding simulator doesn't calculate the percentages correctly.  For example, two 101 Pansies should make a purple (202) pansy 6.5% of the time, not 11% based on the Punnet Squares.  Similarly, blue pansies should be 25%, not 33%.  You can check my math: https://skent259.github.io/ac-flower-factory/basic-hybrids/

**Comment by AeonSake** [comment]
@skent259 You are right. I only calculated all possible gene-combinations, not their possibilities. The resulting %-number is only the sum of gene-combinations / total. I'll update that to give the %-number the real chance value. Thank you!

**Comment by skent259** [comment]
@AeonSake seems to be working great as far as I can tell.  Would you mind if I like to your site from mine?  I also think that screenshots from your sight might help illustrate the guides I'm trying to make on producing tons of flowers.  Would you mind if I included those also?
